#!/usr/bin/env python
#coding=utf-8
import re
import sys
sys.path.append(r'tools')
import read_config_line
def main():
	args = sys.argv
	ACTIONS = re.sub(r'\s','',args[1]).split(':',1)[1]
	allConfig = read_config_line.readConfig()
	print allConfig['dmin-user']
if __name__ == '__main__':
	main()
